import { logoutAdminAction, createCategoryAction, deleteCategoryAction, saveAdAction, updateCategoryAction } from "@/app/admin/actions";
import { AdminPreinscriptions } from "@/components/AdminPreinscriptions";
import { AdminKyc } from "@/components/AdminKyc";
import { requireAdmin } from "@/lib/admin";
import { listPreinscriptions } from "@/lib/preinscripciones";
import { prisma } from "@/lib/prisma";
import { decryptKyc } from "@/lib/kyc";
import { formatARS } from "@/lib/format";
import type { Metadata } from "next";
import { StatusPill } from "@/components/ui";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Administración" };

export default async function AdminPage() {
  await requireAdmin();
  const [preinscriptions, kycCases, users, bookings, categories, ads, userCount, verifiedProviderCount, activeJobCount] = await Promise.all([
    listPreinscriptions(),
    prisma.kycCase.findMany({ orderBy: { updatedAt: "desc" }, include: { documents: true, user: { include: { oauthAccounts: true, professional: true } } } }),
    prisma.user.findMany({ orderBy: { createdAt: "desc" }, take: 50, include: { professional: { select: { providerType: true, profileStatus: true, verified: true } }, oauthAccounts: { select: { provider: true } } } }),
    prisma.booking.findMany({ orderBy: { updatedAt: "desc" }, take: 50, include: { user: { select: { name: true } }, professional: { select: { name: true } }, proposals: { orderBy: { createdAt: "desc" }, take: 1 } } }),
    prisma.category.findMany({ orderBy: [{ kind: "asc" }, { name: "asc" }], include: { _count: { select: { professionals: true, requests: true } } } }),
    prisma.ad.findMany({ orderBy: { slot: "asc" } }),
    prisma.user.count(),
    prisma.professional.count({ where: { verified: true, profileStatus: "approved" } }),
    prisma.booking.count({ where: { status: { in: ["in_progress", "finished", "payment_reported", "paid_awaiting_review"] } } }),
  ]);
  const serializedPreinscriptions = preinscriptions.map((row) => ({ ...row, createdAt: row.createdAt.toISOString() }));
  const serializedKyc = kycCases.map((kyc) => {
    const professional = kyc.user.professional;
    return { id: kyc.id, status: kyc.status, legalName: kyc.legalName, email: kyc.user.email, phone: kyc.phone, cuil: decryptKyc(kyc.cuilEncrypted), dni: decryptKyc(kyc.dniEncrypted), birthDate: kyc.birthDate.toISOString(), address: kyc.address, country: kyc.country, province: kyc.province, locality: kyc.locality, provider: kyc.user.oauthAccounts[0]?.provider || "email", providerType: professional?.providerType || "oficio", headline: professional?.headline || null, bio: professional?.bio || null, paymentAlias: professional?.paymentAlias || null, paymentCvu: professional?.paymentCvu || null, submittedAt: kyc.submittedAt?.toISOString() || null, reviewReason: kyc.reviewReason, reviewedBy: kyc.reviewedBy, reviewedAt: kyc.reviewedAt?.toISOString() || null, videoChallenge: kyc.videoChallenge, documents: kyc.documents.map((document) => ({ id: document.id, kind: document.kind })) };
  });
  const pendingKyc = kycCases.filter((kyc) => kyc.status === "pending").length;

  return <main className="min-h-screen bg-slate-100 px-3 py-4 sm:px-6 sm:py-7"><div className="mx-auto max-w-7xl space-y-8">
    <header className="glass glass-solid rounded-3xl p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cliente">ServiRed Admin</p><h1 className="mt-1 text-3xl font-black text-slate-950">Centro de operaciones</h1><p className="mt-1 text-sm text-slate-500">Identidad, usuarios, trabajos, catálogo y captación en un solo lugar.</p></div><form action={logoutAdminAction}><button className="glass-btn glass-btn-ghost px-4 py-2.5 text-sm">Cerrar sesión</button></form></div>
      <nav className="no-scrollbar mt-5 flex gap-2 overflow-x-auto border-t border-white/70 pt-4 text-sm font-semibold"><a href="#resumen" className="glass-chip px-3 py-2">Resumen</a><a href="#kyc" className="glass-chip px-3 py-2">KYC {pendingKyc ? `(${pendingKyc})` : ""}</a><a href="#usuarios" className="glass-chip px-3 py-2">Usuarios</a><a href="#trabajos" className="glass-chip px-3 py-2">Trabajos</a><a href="#catalogo" className="glass-chip px-3 py-2">Rubros</a><a href="#publicidad" className="glass-chip px-3 py-2">Publicidad</a><a href="#preinscripciones" className="glass-chip px-3 py-2">Preinscripciones</a></nav>
    </header>

    <section id="resumen" className="scroll-mt-24 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Usuarios" value={userCount} note="Cuentas registradas" /><Metric label="Oferentes verificados" value={verifiedProviderCount} note="Perfiles publicados" /><Metric label="KYC pendientes" value={pendingKyc} note="Requieren revisión" danger={pendingKyc > 0} /><Metric label="Trabajos activos" value={activeJobCount} note="Máximo 3 por oferente" /></section>

    <AdminKyc rows={serializedKyc} />

    <section id="usuarios" className="scroll-mt-24 space-y-3"><SectionTitle eyebrow="Cuentas" title="Usuarios y oferentes" subtitle="Últimas 50 altas" /><div className="glass glass-solid overflow-x-auto rounded-2xl"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/55 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Usuario</th><th className="px-4 py-3">Acceso</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Perfil oferente</th><th className="px-4 py-3">Alta</th></tr></thead><tbody className="divide-y divide-white/70">{users.map((user) => <tr key={user.id}><td className="px-4 py-3 font-semibold text-slate-900">{user.name}</td><td className="px-4 py-3 text-slate-600">{user.oauthAccounts[0]?.provider || "email"}</td><td className="px-4 py-3"><span className={user.emailVerifiedAt ? "text-emerald-700" : "text-amber-700"}>{user.email}</span></td><td className="px-4 py-3 text-slate-600">{user.professional ? `${user.professional.providerType} · ${user.professional.profileStatus}` : "Solo Busco"}</td><td className="px-4 py-3 text-slate-500">{user.createdAt.toLocaleDateString("es-AR")}</td></tr>)}</tbody></table></div></section>

    <section id="trabajos" className="scroll-mt-24 space-y-3"><SectionTitle eyebrow="Marketplace" title="Trabajos y propuestas" subtitle="Actividad reciente y estados comerciales" /><div className="glass glass-solid overflow-x-auto rounded-2xl"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-white/55 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Oferente</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Última propuesta</th><th className="px-4 py-3">Actualizado</th></tr></thead><tbody className="divide-y divide-white/70">{bookings.map((booking) => <tr key={booking.id}><td className="px-4 py-3 font-semibold text-slate-900">{booking.user.name}</td><td className="px-4 py-3">{booking.professional.name}</td><td className="px-4 py-3"><StatusPill status={booking.status} /></td><td className="px-4 py-3">{booking.proposals[0] ? `${formatARS(booking.proposals[0].amount)} · ${proposalStatus(booking.proposals[0].status)}` : "—"}</td><td className="px-4 py-3 text-slate-500">{booking.updatedAt.toLocaleString("es-AR")}</td></tr>)}</tbody></table></div></section>

    <section id="catalogo" className="scroll-mt-24 space-y-4"><SectionTitle eyebrow="Clasificación" title="Rubros y categorías" subtitle="Separados entre Profesional y Oficio" /><form action={createCategoryAction} className="glass glass-solid grid gap-3 rounded-2xl p-4 sm:grid-cols-[80px_1fr_1fr_160px_auto]"><input name="icon" placeholder="🛠️" className="glass-field px-3 py-2 text-sm" /><input name="name" required placeholder="Nombre del rubro" className="glass-field px-3 py-2 text-sm" /><input name="slug" placeholder="slug-opcional" className="glass-field px-3 py-2 text-sm" /><select name="kind" className="glass-field px-3 py-2 text-sm"><option value="oficio">Oficio</option><option value="profesional">Profesional</option></select><button className="glass-btn px-4 py-2 text-sm">Agregar</button></form><div className="grid gap-3 md:grid-cols-2">{(["profesional", "oficio"] as const).map((kind) => <div key={kind} className="glass glass-solid rounded-2xl p-4"><h3 className="mb-3 text-lg font-bold capitalize text-slate-900">{kind}</h3><div className="space-y-2">{categories.filter((category) => category.kind === kind).map((category) => <details key={category.id} className="rounded-xl bg-white/60 p-3"><summary className="flex cursor-pointer list-none items-center gap-3"><span className="text-xl">{category.icon}</span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{category.name}</p><p className="text-xs text-slate-400">{category._count.professionals} perfiles · {category._count.requests} solicitudes</p></div><span className="text-xs font-semibold text-cliente">Editar</span></summary><form action={updateCategoryAction} className="mt-3 grid gap-2 border-t border-slate-100 pt-3 sm:grid-cols-[70px_1fr_1fr_130px_auto]"><input type="hidden" name="id" value={category.id} /><input name="icon" defaultValue={category.icon} className="glass-field px-2 py-1.5 text-sm" /><input name="name" required defaultValue={category.name} className="glass-field px-2 py-1.5 text-sm" /><input name="slug" defaultValue={category.slug} className="glass-field px-2 py-1.5 text-sm" /><select name="kind" defaultValue={category.kind} className="glass-field px-2 py-1.5 text-sm"><option value="oficio">Oficio</option><option value="profesional">Profesional</option></select><button className="glass-btn px-3 py-1.5 text-xs">Guardar</button></form><form action={deleteCategoryAction} className="mt-2 text-right"><input type="hidden" name="id" value={category.id} /><button className="text-xs font-semibold text-red-600">Eliminar si no está en uso</button></form></details>)}</div></div>)}</div></section>

    <section id="publicidad" className="scroll-mt-24 space-y-4"><SectionTitle eyebrow="Portada" title="Publicidades" subtitle="Placas laterales y móviles" /><div className="grid gap-3 md:grid-cols-2">{["left-1", "left-2", "right-1", "right-2", "mobile-1", "mobile-2", "mobile-3", "mobile-4"].map((slot) => { const ad = ads.find((item) => item.slot === slot); return <form key={slot} action={saveAdAction} className="glass glass-solid space-y-3 rounded-2xl p-4"><input type="hidden" name="slot" value={slot} /><div className="flex items-center justify-between"><h3 className="font-bold text-slate-900">{slot}</h3><label className="text-xs font-semibold text-slate-600"><input type="checkbox" name="enabled" defaultChecked={ad?.enabled ?? true} className="mr-1" />Activa</label></div><input name="title" required defaultValue={ad?.title || `Publicidad ${slot}`} placeholder="Título" className="glass-field px-3 py-2 text-sm" /><input name="imageUrl" defaultValue={ad?.imageUrl || ""} placeholder="URL de imagen" className="glass-field px-3 py-2 text-sm" /><input name="linkUrl" defaultValue={ad?.linkUrl || ""} placeholder="Enlace de destino" className="glass-field px-3 py-2 text-sm" /><button className="glass-btn px-4 py-2 text-sm">Guardar placa</button></form>; })}</div></section>

    <section id="preinscripciones" className="scroll-mt-24"><SectionTitle eyebrow="Captación" title="Preinscripciones" subtitle={`${preinscriptions.length} contactos únicos`} /><AdminPreinscriptions initialRows={serializedPreinscriptions} /></section>
  </div></main>;
}

function Metric({ label, value, note, danger = false }: { label: string; value: number; note: string; danger?: boolean }) { return <article className={`glass glass-solid rounded-2xl border-t-4 p-4 ${danger ? "border-t-amber-500" : "border-t-cliente"}`}><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><strong className="mt-1 block text-3xl text-slate-950">{value}</strong><p className="text-xs text-slate-400">{note}</p></article>; }
function SectionTitle({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <div><p className="text-xs font-bold uppercase tracking-[.16em] text-cliente">{eyebrow}</p><h2 className="text-2xl font-bold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{subtitle}</p></div>; }
function proposalStatus(status: string) { return ({ pending: "pendiente", accepted: "aceptada", rejected: "rechazada", expired: "vencida" } as Record<string, string>)[status] || status; }
